server:
  port: 8082
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/comments_blocker_admin_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    platform: postgresql
    hikari:
      maximum-pool-size: 60
      minimum-idle: 60
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, logfile, metrics
      base-path: /monitoring
  endpoint:
    health:
      enabled: true
      show-components: when_authorized
      show-details: when_authorized
      roles: ADMIN
      cache:
        time-to-live: 5000
    info:
      enabled: true
    env:
      enabled: true
    heartbeat:
      enabled: true
    logfile:
      enabled: true
    metrics:
      enabled: true
  level:
    root: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
com:
  whoisacat:
    commentsBlocker:
      service:
        fileName: /blocker_files/ip_block.txt
        fileUpdatePeriod: 5
      health:
        heartbeat:
          period: 1000
