version: '3'
services:
  admin:
    container_name: blocker_admin
    image: whoisacat/ura_comments_blocker_admin:test
    privileged: true
    ports:
      - "8081:8081"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/comments_blocker_admin_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=postgres:5432
    depends_on:
      - db
    networks:
      - comments_blocker_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "updater:8081" ]
      interval: 30s
      timeout: 10s
      retries: 5
  updater:
    container_name: blocker_updater
    image: whoisacat/ura_comments_blocker_updater:test
    privileged: true
    ports:
      - "8082:8082"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/comments_blocker_admin_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=admin:8081
    restart: on-failure
    depends_on:
      - admin
    volumes:
      - /Путь_до_папки:/blocker_files
    networks:
      - comments_blocker_network
  db:
    container_name: blocker_db
    image: postgres:12
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comments_blocker_admin_db
    networks:
      - comments_blocker_network
    volumes:
      - dbdata:/var/lib/postgresql/data
networks:
  comments_blocker_network:
    driver: bridge
volumes:
  blocker_files:
  dbdata: